services:
  postgres:
    image: postgres:16
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: london_bike_share
    volumes:
      - ./london_bike_share_data:/var/lib/postgresql/data
      - ./postgres/init_airflow.sql:/docker-entrypoint-initdb.d/init_airflow.sql
    ports:
      - "5432:5432"
    networks:
      - london-bike-share-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d london_bike_share"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"
    networks:
      - london-bike-share-network
    depends_on:
      postgres:
        condition: service_healthy

  bike_ingest:
    build:
      context: .
      dockerfile: app/local_ingestion/Dockerfile
    image: bike_ingest:v001
    container_name: bike_ingest
    networks:
      - london-bike-share-network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - ingest
    command: >
      --pg-user=root
      --pg-pass=root
      --pg-host=postgres
      --pg-port=5432

  airflow-init:
    build:
      context: ./orchestration/airflow
      dockerfile: Dockerfile
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://root:root@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_shared_airflow_secret_key"
    volumes:
      - ./orchestration/airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@admin.com"
    networks:
      - london-bike-share-network

  airflow-webserver:
    build:
      context: ./orchestration/airflow
      dockerfile: Dockerfile
    container_name: airflow-webserver
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://root:root@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_shared_airflow_secret_key"
    volumes:
      - ./orchestration/airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    ports:
      - "8081:8080"
    command: webserver
    networks:
      - london-bike-share-network

  airflow-scheduler:
    build:
      context: ./orchestration/airflow
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://root:root@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_shared_airflow_secret_key"
    volumes:
      - ./orchestration/airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    command: scheduler
    networks:
      - london-bike-share-network

volumes:
  pgadmin_data:

networks:
  london-bike-share-network:
    driver: bridge